version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.23
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
      - run:
          name: Build and Tag Docker Images
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-api-feed hideonhp/udagram-api-feed:v1.2
            docker tag udagram-api-user hideonhp/udagram-api-user:v1.2
            docker tag udagram-reverseproxy hideonhp/udagram-reverseproxy:v1.2
            docker tag udagram-frontend hideonhp/udagram-frontend:v1.2
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push hideonhp/udagram-api-feed:v1.2
            docker push hideonhp/udagram-api-user:v1.2
            docker push hideonhp/udagram-reverseproxy:v1.2
            docker push hideonhp/udagram-frontend:v1.2
workflows:
  version: 3
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main