version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build and Tag Docker Images
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-api-feed hideonhp/udagram-api-feed:v2
            docker tag udagram-api-user hideonhp/udagram-api-user:v2
            docker tag udagram-reverseproxy hideonhp/udagram-reverseproxy:v2
            docker tag udagram-frontend hideonhp/udagram-frontend:v2
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push hideonhp/udagram-api-feed:v2
            docker push hideonhp/udagram-api-user:v2
            docker push hideonhp/udagram-reverseproxy:v2
            docker push hideonhp/udagram-frontend:v2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main