version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      # Install Docker
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      # Build Docker images
      - run:
          name: Build Docker images
          command: |
            docker --version
            docker build -t hideonhp/udagram-reverseproxy:latest -f ./udagram-reverseproxy/Dockerfile ./udagram-reverseproxy
            docker build -t hideonhp/udagram-api-feed:latest -f ./udagram-api-feed/Dockerfile ./udagram-api-feed
            docker build -t hideonhp/udagram-api-user:latest -f ./udagram-api-user/Dockerfile ./udagram-api-user
            docker build -t hideonhp/udagram-frontend:latest -f ./udagram-frontend/Dockerfile ./udagram-frontend

      # Log in to Docker Hub and push Docker images
      - run:
          name: Push Docker images to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push hideonhp/udagram-reverseproxy:latest
            docker push hideonhp/udagram-api-feed:latest
            docker push hideonhp/udagram-api-user:latest
            docker push hideonhp/udagram-frontend:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
