version: 2.1

jobs:
  build_api_feed:
    docker:
      - image: docker:20.10.23
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
      - run:
          name: Build Docker Image for udagram-api-feed
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed hideonhp/udagram-api-feed:v2
            docker images

  build_api_user:
    docker:
      - image: docker:20.10.23
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
      - run:
          name: Build Docker Image for udagram-api-user
          command: |
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user hideonhp/udagram-api-user:v2
            docker images

  build_reverseproxy:
    docker:
      - image: docker:20.10.23
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
      - run:
          name: Build Docker Image for udagram-reverseproxy
          command: |
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy hideonhp/udagram-reverseproxy:v2
            docker images

  build_frontend:
    docker:
      - image: docker:20.10.23
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
      - run:
          name: Build Docker Image for udagram-frontend
          command: |
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend hideonhp/udagram-frontend:v2
            docker images

  push_docker_images:
    docker:
      - image: docker:20.10.23
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
      - run:
          name: Push Docker Images to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push hideonhp/udagram-api-feed:v2
            docker push hideonhp/udagram-api-user:v2
            docker push hideonhp/udagram-reverseproxy:v2
            docker push hideonhp/udagram-frontend:v2

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_api_feed
      - build_api_user
      - build_reverseproxy
      - build_frontend
      - push_docker_images:
          requires:
            - build_api_feed
            - build_api_user
            - build_reverseproxy
            - build_frontend
          filters:
            branches:
              only:
                - main
