apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hideonhp/udagram-frontend:v1.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2000Mi"
            cpu: "250m"
          limits:
            memory: "4000Mi"
            cpu: "500m"
          